/**
 * Lounge Asia Feeds Script
 * Handles fetching and displaying content from Instagram and Meetup.
 */

document.addEventListener('DOMContentLoaded', () => {
    initInstagramFeed();
    initMeetupFeed();
});

/**
 * Instagram Feed Integration
 * Note: To display real data, you need to connect your account via a service like Behold.so
 * and replace the FEED_URL below.
 */
function initInstagramFeed() {
    const container = document.getElementById('instagram-feed-container');
    if (!container) return;

    // CONFIGURATION: Replace this URL with your actual feed JSON URL from Behold.so or similar
    const FEED_URL = 'https://feeds.behold.so/7d5XSu3SRu6EpNpo755e'; 
    
    // Placeholder data to show before integration is complete
    const placeholders = [
        { url: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=400&q=80', caption: 'Great exciting atmosphere!' },
        { url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=400&q=80', caption: 'Networking with friends' },
        { url: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=400&q=80', caption: 'Join our community' },
        { url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=400&q=80', caption: 'Diverse group of people' },
        { url: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=400&q=80', caption: 'Friday night drinks' },
        { url: 'https://images.unsplash.com/photo-1576267423048-15c0040fec78?auto=format&fit=crop&w=400&q=80', caption: 'Making memories' }
    ];

    if (!FEED_URL) {
        renderInstagramGrid(placeholders, container, true);
        return;
    }

    fetch(FEED_URL)
        .then(response => response.json())
        .then(data => {
            // Support both array response and object with 'posts' key
            const feedItems = Array.isArray(data) ? data : (data.posts || []);
            
            const posts = feedItems.map(item => ({
                url: (item.mediaType === 'VIDEO' || item.mediaType === 'REEL') ? (item.thumbnailUrl || item.mediaUrl) : item.mediaUrl,
                caption: item.caption || '',
                permalink: item.permalink || 'https://instagram.com/_lounge_asia'
            })).slice(0, 6);
            
            renderInstagramGrid(posts, container);
        })
        .catch(err => {
            console.warn('Instagram feed failed to load, falling back to placeholders', err);
            renderInstagramGrid(placeholders, container, true);
        });
}

function renderInstagramGrid(posts, container, isPlaceholder = false) {
    container.innerHTML = '';
    
    posts.forEach(post => {
        const item = document.createElement('div');
        item.className = 'group relative overflow-hidden rounded-xl aspect-square card-glow';
        
        const link = document.createElement('a');
        link.href = post.permalink || 'https://instagram.com/_lounge_asia';
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        link.className = 'block w-full h-full';

        const img = document.createElement('img');
        img.src = post.url;
        img.alt = post.caption || 'Instagram Post';
        img.className = 'w-full h-full object-cover transition-transform duration-500 group-hover:scale-110';
        img.loading = 'lazy';

        // Overlay with icon
        const overlay = document.createElement('div');
        overlay.className = 'absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center';
        overlay.innerHTML = '<span class="text-white text-3xl"><i class="fab fa-instagram"></i></span>'; // Assuming FontAwesome or similar, or use SVG

        link.appendChild(img);
        link.appendChild(overlay);
        item.appendChild(link);
        container.appendChild(item);
    });

    if (isPlaceholder) {
        const notice = document.createElement('div');
        notice.className = 'col-span-full text-center text-xs text-gray-500 mt-2';
        notice.textContent = 'Follow us @_lounge_asia (Preview Mode)';
        container.appendChild(notice);
    }
}

/**
 * Meetup Feed Integration
 * Fetches events from a static JSON file generated by a daily GitHub Action.
 */
function initMeetupFeed() {
    const container = document.getElementById('meetup-events-container');
    if (!container) return;

    // Fetch from local JSON file
    fetch('assets/events.json')
        .then(response => {
            if (!response.ok) throw new Error('Network response was not ok');
            return response.json();
        })
        .then(data => {
            if (Array.isArray(data) && data.length > 0) {
                const upcomingEvents = filterAndSortEvents(data);
                
                if (upcomingEvents.length > 0) {
                    renderMeetupEvents(upcomingEvents, container);
                    updateHeroLinks(upcomingEvents);
                } else {
                    renderFallbackEvents(container);
                }
            } else {
                renderFallbackEvents(container);
            }
        })
        .catch(err => {
            console.warn('Failed to load local Meetup events, falling back to manual list.', err);
            renderFallbackEvents(container);
        });
}

function renderFallbackEvents(container) {
    // Manual fallback events provided by user
    const manualEvents = [
        {
            title: "TUE NIGHT Asian Background Social: Lounge Asia Meetup (Easy English)",
            pubDate: "2026-01-06 18:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/312431792/",
            venue: "Brisbane"
        },
        {
            title: "⚠️ [CHANGE OF DATE & VENUE] Asian Background Social: Lounge Asia Meetup",
            pubDate: "2026-01-10 18:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/309390234/",
            venue: "Sydney"
        },
        {
            title: "WED NIGHT Asian Background Social: Lounge Asia Meetup (Easy English) @ Melbourne",
            pubDate: "2026-01-21 18:00:00",
            link: "https://www.meetup.com/ja-jp/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/312512043/",
            venue: "Melbourne"
        },
        {
            title: "Global Asian Social: Lounge Asia Meetup @ Tokyo",
            pubDate: "2026-02-09 10:23:23", 
            link: "https://www.meetup.com/ja-jp/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/313276852/",
            venue: "Tokyo",
            eventDate: "2026-02-22T07:00:00.000Z"
        }
    ];

    const upcomingEvents = filterAndSortEvents(manualEvents);
    if (upcomingEvents.length > 0) {
         renderMeetupEvents(upcomingEvents, container);
         updateHeroLinks(upcomingEvents);
    } else {
        renderNoEvents(container, `https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/`);
    }
}

/**
 * Filter events to show only future ones and sort by date (nearest first).
 * @param {Array} events - List of event objects from RSS feed
 * @returns {Array} - Sorted list of upcoming events
 */
/**
 * Filter events to show only future ones and sort by date.
 * @param {Array} events - List of event objects
 * @returns {Array} - Sorted list of upcoming events
 */
/**
 * Filter events to sort by date (trusting feed content).
 * @param {Array} events - List of event objects
 * @returns {Array} - Sorted list of events
 */
function filterAndSortEvents(events) {
    return events.sort((a, b) => {
        // Sort by eventDate/pubDate descending (newest published/detected first)
        const dateA = new Date(a.eventDate || a.pubDate);
        const dateB = new Date(b.eventDate || b.pubDate);
        return dateB - dateA;
    });
}

function renderMeetupEvents(events, container) {
    container.innerHTML = '';
    const list = document.createElement('div');
    list.className = 'grid gap-6 md:grid-cols-2 lg:grid-cols-3';

    // City icon and color mapping
    const cityConfigs = {
        'Brisbane': { icon: '🐨', color: 'bg-green-500/20 text-green-400 border-green-500/30', timezone: 'Australia/Brisbane' },
        'Sydney': { icon: '🌉', color: 'bg-blue-500/20 text-blue-400 border-blue-500/30', timezone: 'Australia/Sydney' },
        'Melbourne': { icon: '☕', color: 'bg-purple-500/20 text-purple-400 border-purple-500/30', timezone: 'Australia/Melbourne' },
        'Tokyo': { icon: '🗼', color: 'bg-red-500/20 text-red-400 border-red-500/30', timezone: 'Asia/Tokyo' }
    };

    // Strategy: Select the next upcoming event for each distinct city first
    const uniqueCityEvents = [];
    const citiesFound = new Set();

    // 1. First pass: Find first event for each supported city
    ['Brisbane', 'Sydney', 'Melbourne', 'Tokyo'].forEach(city => {
        const event = events.find(e => {
            const venue = e.venue || 'Brisbane'; // Fallback
            // Check if venue matches (loose check)
            return venue.toLowerCase().includes(city.toLowerCase());
        });
        
        if (event) {
            uniqueCityEvents.push(event);
            citiesFound.add(event.link); // Use link as unique ID
        }
    });

    // 2. Second pass: Fill remaining slots (up to 3) with other events
    // Filter out already selected events
    const remainingEvents = events.filter(e => !citiesFound.has(e.link));
    
    // Combine and slice
    let displayList = [...uniqueCityEvents, ...remainingEvents];
    
    // Deduplicate just in case
    displayList = displayList.reduce((acc, current) => {
        const x = acc.find(item => item.link === current.link);
        if (!x) {
            return acc.concat([current]);
        } else {
            return acc;
        }
    }, []).slice(0, 4); // Increased to 4 to accomodate Tokyo if all 4 cities have events
    
    // Sort logic for display: Group by city or just list?
    // Let's just keep the order we found them (Proximity/Priority) or sort by city?
    // User asked for "each city", so our priority selection is good.

    displayList.forEach(event => {
        const card = document.createElement('article');
        card.className = 'bg-gray-800/80 backdrop-blur-sm rounded-xl overflow-hidden shadow-lg hover:shadow-2xl hover:-translate-y-1 transition-all duration-300 border border-gray-700 hover:border-brand-primary/30 flex flex-col relative group';

        const city = event.venue || 'Brisbane';
        // Normalize city key for config
        let configKey = 'Brisbane';
        if (city.includes('Sydney')) configKey = 'Sydney';
        if (city.includes('Melbourne')) configKey = 'Melbourne';
        if (city.includes('Tokyo')) configKey = 'Tokyo';
        
        // Simplified sleek config - minimal colors
        const cityInfo = cityConfigs[configKey] || cityConfigs['Brisbane'];
        
        const cityDisplay = {
            'Brisbane': { short: 'BNE', label: 'Brisbane' },
            'Sydney': { short: 'SYD', label: 'Sydney' },
            'Melbourne': { short: 'MEL', label: 'Melbourne' },
            'Tokyo': { short: 'TYO', label: 'Tokyo' }
        }[configKey] || { short: 'BNE', label: 'Brisbane' };

        // Format Date
        const dateObj = new Date(event.eventDate);
        const timeStr = dateObj.toLocaleTimeString('en-US', { 
            hour: 'numeric', 
            minute: '2-digit',
            timeZone: (cityConfigs[configKey] || {}).timezone || 'Australia/Brisbane'
        });
        // Optional: Manual override for Tokyo if needed, but better to use real data
        
        card.innerHTML = `
            <div class="p-8 flex flex-col h-full items-center text-center relative z-10">
                
                <!-- City Display - Premium/Editorial Style -->
                <div class="mb-6 relative">
                    <h3 class="text-4xl md:text-5xl font-black text-transparent bg-clip-text bg-gradient-to-b from-white to-gray-500 uppercase tracking-tighter">
                        ${cityDisplay.label}
                    </h3>
                    <div class="h-1 w-12 bg-brand-primary rounded-full mx-auto mt-2 opacity-80"></div>
                </div>

                <!-- Fixed Time Removed as per user request -->
                
                <!-- Registration Notice -->
                <div class="w-full bg-gray-900/50 border border-gray-700/50 rounded-lg p-4 mb-8">
                    <div class="flex items-center justify-center gap-2 text-gray-400 text-sm mb-1">
                        <span class="text-brand-primary">ℹ️</span>
                        <span class="font-medium text-gray-300">Registration Required</span>
                    </div>
                    <p class="text-gray-500 text-xs text-center leading-relaxed">
                        Please RSVP on Meetup to join.
                    </p>
                </div>

                <div class="mt-auto w-full">
                    <a href="${event.link}" target="_blank" class="block w-full bg-white text-black hover:bg-brand-primary hover:text-white font-bold py-4 px-6 rounded-lg transition-all duration-300 shadow-lg uppercase tracking-wider text-sm">
                        RSVP Now
                    </a>
                </div>
            </div>
            
            <!-- Subtle Decorative Element -->
            <div class="absolute top-0 right-0 p-4 opacity-10 text-6xl font-black select-none pointer-events-none text-white overflow-hidden">
                ${cityDisplay.short}
            </div>
        `;
        list.appendChild(card);
    });

    container.appendChild(list);
}

function renderNoEvents(container, groupUrl) {
    container.innerHTML = `
        <div class="text-center bg-gray-800/50 p-8 rounded-xl border border-gray-700 border-dashed">
            <p class="text-gray-300 text-lg mb-2">No upcoming events scheduled right now.</p>
            <p class="text-gray-500 text-sm">Join our Meetup group to get notified when we post one!</p>
            <a href="${groupUrl}" target="_blank" class="inline-block mt-4 text-yellow-500 hover:text-yellow-400 font-semibold">
                Visit our Meetup Page &rarr;
            </a>
        </div>
    `;
}

/**
 * Updates the "Meet Your Local Heroes" section links based on upcoming events.
 * Maps specific hosts to their city's next event.
 * @param {Array} events - Sorted list of upcoming events
 */
function updateHeroLinks(events) {
    // Map host IDs to their respective City keywords
    const hostMap = {
        'host-chris': 'Sydney',
        'host-david': 'Melbourne',
        'host-naoki': 'Brisbane',
        'host-kazuma': 'Tokyo',
        'host-hiroshi': 'Fukuoka'
        // Michael is static
    };

    // Default Main Link
    const mainLink = 'https://www.meetup.com/ja-JP/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr';

    Object.keys(hostMap).forEach(hostId => {
        const element = document.getElementById(hostId);
        if (element) {
            const cityKeyword = hostMap[hostId];
            
            // Find the *first* upcoming event for this city
            // Events are already sorted by date in filterAndSortEvents
            const cityEvent = events.find(e => {
                const venue = e.venue || '';
                return venue.toLowerCase().includes(cityKeyword.toLowerCase());
            });

            if (cityEvent && cityEvent.link) {
                element.href = cityEvent.link;
            } else {
                // If no specific event, link to main group page (or keep default if hardcoded)
                // We'll set it to main group page to be safe
                element.href = mainLink;
            }
        }
    });

    // Fukuoka specific handling (since we might no have events yet)
    // If Hiroshi needs a specific fallback (e.g. no events yet), it defaults to mainLink above.
}
