/**
 * Lounge Asia Feeds Script
 * Handles fetching and displaying content from Instagram and Meetup.
 */

document.addEventListener('DOMContentLoaded', () => {
    initInstagramFeed();
    initMeetupFeed();
});

/**
 * Instagram Feed Integration
 * Note: To display real data, you need to connect your account via a service like Behold.so
 * and replace the FEED_URL below.
 */
function initInstagramFeed() {
    const container = document.getElementById('instagram-feed-container');
    if (!container) return;

    // CONFIGURATION: Replace this URL with your actual feed JSON URL from Behold.so or similar
    const FEED_URL = 'https://feeds.behold.so/7d5XSu3SRu6EpNpo755e'; 
    
    // Placeholder data to show before integration is complete
    const placeholders = [
        { url: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=400&q=80', caption: 'Great exciting atmosphere!' },
        { url: 'https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=400&q=80', caption: 'Networking with friends' },
        { url: 'https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=400&q=80', caption: 'Join our community' },
        { url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=400&q=80', caption: 'Diverse group of people' },
        { url: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=400&q=80', caption: 'Friday night drinks' },
        { url: 'https://images.unsplash.com/photo-1576267423048-15c0040fec78?auto=format&fit=crop&w=400&q=80', caption: 'Making memories' }
    ];

    if (!FEED_URL) {
        renderInstagramGrid(placeholders, container, true);
        return;
    }

    fetch(FEED_URL)
        .then(response => response.json())
        .then(data => {
            // Support both array response and object with 'posts' key
            const feedItems = Array.isArray(data) ? data : (data.posts || []);
            
            const posts = feedItems.map(item => ({
                url: (item.mediaType === 'VIDEO' || item.mediaType === 'REEL') ? (item.thumbnailUrl || item.mediaUrl) : item.mediaUrl,
                caption: item.caption || '',
                permalink: item.permalink || 'https://instagram.com/_lounge_asia'
            })).slice(0, 6);
            
            renderInstagramGrid(posts, container);
        })
        .catch(err => {
            console.warn('Instagram feed failed to load, falling back to placeholders', err);
            renderInstagramGrid(placeholders, container, true);
        });
}

function renderInstagramGrid(posts, container, isPlaceholder = false) {
    container.innerHTML = '';
    
    posts.forEach(post => {
        const item = document.createElement('div');
        item.className = 'group relative overflow-hidden rounded-xl aspect-square card-glow';
        
        const link = document.createElement('a');
        link.href = post.permalink || 'https://instagram.com/_lounge_asia';
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        link.className = 'block w-full h-full';

        const img = document.createElement('img');
        img.src = post.url;
        img.alt = post.caption || 'Instagram Post';
        img.className = 'w-full h-full object-cover transition-transform duration-500 group-hover:scale-110';
        img.loading = 'lazy';

        // Overlay with icon
        const overlay = document.createElement('div');
        overlay.className = 'absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center';
        overlay.innerHTML = '<span class="text-white text-3xl"><i class="fab fa-instagram"></i></span>'; // Assuming FontAwesome or similar, or use SVG

        link.appendChild(img);
        link.appendChild(overlay);
        item.appendChild(link);
        container.appendChild(item);
    });

    if (isPlaceholder) {
        const notice = document.createElement('div');
        notice.className = 'col-span-full text-center text-xs text-gray-500 mt-2';
        notice.textContent = 'Follow us @_lounge_asia (Preview Mode)';
        container.appendChild(notice);
    }
}

/**
 * Meetup Feed Integration
 * Fetches events from a static JSON file generated by a daily GitHub Action.
 */
function initMeetupFeed() {
    const container = document.getElementById('meetup-events-container');
    if (!container) return;

    // Fetch from local JSON file
    fetch('assets/events.json')
        .then(response => {
            if (!response.ok) throw new Error('Network response was not ok');
            return response.json();
        })
        .then(data => {
            let events = Array.isArray(data) ? data : [];
            
            // Manual Event Injection (Tokyo, Riyadh, Dubai, HCMC, Fukuoka)
            const manualInjections = [
                {
                    city: 'Tokyo',
                    event: {
                        title: "Global Asian Social: Lounge Asia Meetup @ Tokyo",
                        pubDate: "2026-02-09 10:23:23", 
                        link: "https://www.meetup.com/ja-jp/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/313276852/",
                        venue: "Tokyo",
                        eventDate: "2026-02-22T07:00:00.000Z",
                        description: "Join us in Tokyo for our global mixer event!"
                    }
                },
                {
                    city: 'Riyadh',
                    event: {
                        title: "Global Asian Social: Lounge Asia Meetup @ Riyadh",
                        pubDate: "2026-02-12 10:00:00",
                        link: "https://www.meetup.com/ja-jp/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/313320977", 
                        venue: "Riyadh",
                        eventDate: "2026-03-01T18:00:00.000Z",
                        description: "Join us in Riyadh!"
                    }
                },
                {
                    city: 'Dubai',
                    event: {
                        title: "Global Asian Social: Lounge Asia Meetup @ Dubai",
                        pubDate: "2026-02-12 10:00:00",
                        link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/313321443",
                        venue: "Dubai",
                        eventDate: "2026-03-02T18:00:00.000Z",
                        description: "Join us in Dubai!"
                    }
                },
                {
                    city: 'Ho Chi Minh City',
                    event: {
                        title: "Global Asian Social: Lounge Asia Meetup @ Ho Chi Minh City",
                        pubDate: "2026-02-12 10:00:00",
                        link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/?venue=hcmc",
                        venue: "Ho Chi Minh City",
                        eventDate: "2026-03-03T18:00:00.000Z",
                        description: "Join us in HCMC!"
                    }
                },
                {
                    city: 'Fukuoka',
                    event: {
                        title: "Global Asian Social: Lounge Asia Meetup @ Fukuoka",
                        pubDate: "2026-02-12 10:00:00",
                        link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/?venue=fukuoka",
                        venue: "Fukuoka",
                        eventDate: "2026-03-04T18:00:00.000Z",
                        description: "Join us in Fukuoka!"
                    }
                }
            ];

            manualInjections.forEach(item => {
                const hasCity = events.some(e => (e.venue && e.venue.includes(item.city)) || (e.title && e.title.includes(item.city)));
                if (!hasCity) {
                   console.log(`Injecting manual ${item.city} event`);
                   events.push(item.event);
                }
            });

            if (events.length > 0) {
                const upcomingEvents = filterAndSortEvents(events);
                
                if (upcomingEvents.length > 0) {
                    renderMeetupEvents(upcomingEvents, container);
                    updateHeroLinks(upcomingEvents);
                } else {
                    renderFallbackEvents(container);
                }
            } else {
                renderFallbackEvents(container);
            }
        })
        .catch(err => {
            console.warn('Failed to load local Meetup events, falling back to manual list.', err);
            renderFallbackEvents(container);
        });
}

function renderFallbackEvents(container) {
    // Manual fallback events provided by user
    const manualEvents = [
        {
            title: "TUE NIGHT Asian Background Social: Lounge Asia Meetup (Easy English)",
            pubDate: "2026-01-06 18:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/312431792/",
            venue: "Brisbane"
        },
        {
            title: "⚠️ [CHANGE OF DATE & VENUE] Asian Background Social: Lounge Asia Meetup",
            pubDate: "2026-01-10 18:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/309390234/",
            venue: "Sydney"
        },
        {
            title: "WED NIGHT Asian Background Social: Lounge Asia Meetup (Easy English) @ Melbourne",
            pubDate: "2026-01-21 18:00:00",
            link: "https://www.meetup.com/ja-jp/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/312512043/",
            venue: "Melbourne"
        },
        {
            title: "Global Asian Social: Lounge Asia Meetup @ Tokyo",
            pubDate: "2026-02-09 10:23:23", 
            link: "https://www.meetup.com/ja-jp/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/313276852/",
            venue: "Tokyo",
            eventDate: "2026-02-22T07:00:00.000Z"
        },
        {
            title: "Global Asian Social: Lounge Asia Meetup @ Riyadh",
            pubDate: "2026-02-12 10:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp",
            venue: "Riyadh",
            eventDate: "2026-03-01T18:00:00.000Z" // Placeholder date
        },
        {
            title: "Global Asian Social: Lounge Asia Meetup @ Dubai",
            pubDate: "2026-02-12 10:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/events/313321443",
            venue: "Dubai",
            eventDate: "2026-03-02T18:00:00.000Z" // Placeholder date derived from link context if possible, otherwise generic future
        },
         {
            title: "Global Asian Social: Lounge Asia Meetup @ Ho Chi Minh City",
            pubDate: "2026-02-12 10:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/",
            venue: "Ho Chi Minh City",
            eventDate: "2026-03-03T18:00:00.000Z" // Placeholder
        },
        {
            title: "Global Asian Social: Lounge Asia Meetup @ Fukuoka",
            pubDate: "2026-02-12 10:00:00",
            link: "https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/",
            venue: "Fukuoka",
            eventDate: "2026-03-04T18:00:00.000Z" // Placeholder
        }
    ];

    const upcomingEvents = filterAndSortEvents(manualEvents);
    if (upcomingEvents.length > 0) {
         renderMeetupEvents(upcomingEvents, container);
         updateHeroLinks(upcomingEvents);
    } else {
        renderNoEvents(container, `https://www.meetup.com/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr/`);
    }
}

/**
 * Filter events to show only future ones and sort by date (nearest first).
 * @param {Array} events - List of event objects from RSS feed
 * @returns {Array} - Sorted list of upcoming events
 */
/**
 * Filter events to show only future ones and sort by date.
 * @param {Array} events - List of event objects
 * @returns {Array} - Sorted list of upcoming events
 */
/**
 * Filter events to sort by date (trusting feed content).
 * @param {Array} events - List of event objects
 * @returns {Array} - Sorted list of events
 */
function filterAndSortEvents(events) {
    return events.sort((a, b) => {
        // Sort by eventDate/pubDate descending (newest published/detected first)
        const dateA = new Date(a.eventDate || a.pubDate);
        const dateB = new Date(b.eventDate || b.pubDate);
        return dateB - dateA;
    });
}

function renderMeetupEvents(events, container) {
    container.innerHTML = '';
    
    // Change container class for responsive layout: 
    // - Mobile: Horizontal Scroll (flex + overflow-x-auto)
    // - Desktop: Grid (md:grid)
    const list = document.createElement('div');
    list.className = 'flex overflow-x-auto gap-4 pb-4 md:grid md:gap-6 md:grid-cols-2 lg:grid-cols-3 snap-x snap-mandatory scrollbar-hide no-scrollbar';
    list.style.cssText = '-ms-overflow-style: none; scrollbar-width: none;'; // Hide scrollbar cleanly

    // SVG Icons (Monochrome, Premium)
    const icons = {
        brisbane: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" stroke-linecap="round" stroke-linejoin="round"></path></svg>', 
        // Custom Opera House Path attempting to match the "gold line art" feel but reusing the unified white style
        sydney: '<svg class="w-16 h-16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><path d="M4 21h17M3 19h18M5.5 19l.5-6s.5-3 4-3 3 5 3 5M9 19l1-8s1-4 4-2 2 6 2 6M15 19l1-5s1-3 3-2 2 5 2 5M12 19V9M7 19v-4"/></svg>', 
        melbourne: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" stroke-linecap="round" stroke-linejoin="round"></path></svg>', 
        tokyo: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M12 21V3m0 0L8.25 7.5M12 3l3.75 4.5M12 9a4.5 4.5 0 100 9 4.5 4.5 0 000-9zM3 21h18" stroke-linecap="round" stroke-linejoin="round"></path></svg>', 
        fukuoka: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M4.5 10.5L12 3l7.5 7.5M3 21h18v-9H3v9zm9-6v3" stroke-linecap="round" stroke-linejoin="round"></path></svg>',
        hcmc: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M12 21a9.004 9.004 0 008.716-6.747M12 21a9.004 9.004 0 01-8.716-6.747M12 21c2.485 0 4.5-4.03 4.5-9S14.485 3 12 3m0 18c-2.485 0-4.5-4.03-4.5-9S9.515 3 12 3m0 0a8.997 8.997 0 017.843 4.582M12 3a8.997 8.997 0 00-7.843 4.582m15.686 0A11.953 11.953 0 0112 10.5c-2.998 0-5.74-1.1-7.843-2.918m15.686 0A8.959 8.959 0 0121 12c0 .778-.099 1.533-.284 2.253m0 0A17.919 17.919 0 0112 16.5c-3.162 0-6.133-.815-8.716-2.247m0 0A9.015 9.015 0 013 12c0-1.605.546-3.131 1.457-4.373" stroke-linecap="round" stroke-linejoin="round"></path></svg>', 
        riyadh: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" stroke-linecap="round" stroke-linejoin="round"></path></svg>', 
        dubai: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M12 21V3m0 0l-9 9m9-9l9 9" stroke-linecap="round" stroke-linejoin="round"></path></svg>', 
        global: '<svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="1"><path d="M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9" stroke-linecap="round" stroke-linejoin="round"></path></svg>', 
    };

    // City Configs with Fallback Logic implied
    const cityConfigs = {
        'Brisbane': { icon: icons.brisbane, timezone: 'Australia/Brisbane', label: 'Brisbane', short: 'BNE' },
        'Sydney': { icon: icons.sydney, timezone: 'Australia/Sydney', label: 'Sydney', short: 'SYD' },
        'Melbourne': { icon: icons.melbourne, timezone: 'Australia/Melbourne', label: 'Melbourne', short: 'MEL' },
        'Tokyo': { icon: icons.tokyo, timezone: 'Asia/Tokyo', label: 'Tokyo', short: 'TYO' },
        'Fukuoka': { icon: icons.fukuoka, timezone: 'Asia/Tokyo', label: 'Fukuoka', short: 'FUK' },
        'Ho Chi Minh City': { icon: icons.hcmc, timezone: 'Asia/Ho_Chi_Minh', label: 'Ho Chi Minh', short: 'SGN' },
        'Riyadh': { icon: icons.riyadh, timezone: 'Asia/Riyadh', label: 'Riyadh', short: 'RUH' },
        'Dubai': { icon: icons.dubai, timezone: 'Asia/Dubai', label: 'Dubai', short: 'DXB' },
        'Global': { icon: icons.global, timezone: 'UTC', label: 'Global', short: 'GLO' }
    };

    // Helper to get city config
    function getCityConfig(venue) {
        if (!venue) return cityConfigs['Global'];
        const v = venue.toLowerCase();
        if (v.includes('brisbane') || v.includes('gold coast') || v.includes('sunshine')) return cityConfigs['Brisbane'];
        if (v.includes('sydney') || v.includes('newcastle')) return cityConfigs['Sydney'];
        if (v.includes('melbourne')) return cityConfigs['Melbourne'];
        if (v.includes('tokyo') || v.includes('yokohama')) return cityConfigs['Tokyo'];
        if (v.includes('fukuoka')) return cityConfigs['Fukuoka'];
        if (v.includes('ho chi minh') || v.includes('saigon')) return cityConfigs['Ho Chi Minh City'];
        if (v.includes('riyadh')) return cityConfigs['Riyadh'];
        if (v.includes('dubai')) return cityConfigs['Dubai'];
        return cityConfigs['Global']; // Fallback for unknown cities
    }

    // Strategy: Select the next upcoming event for each distinct city first
    const uniqueCityEvents = [];
    const citiesFound = new Set();
    const cityPriorities = ['Brisbane', 'Sydney', 'Melbourne', 'Tokyo', 'Riyadh', 'Dubai', 'Ho Chi Minh City', 'Fukuoka'];

    // 1. First pass: Find first event for each supported city
    cityPriorities.forEach(cityKeyword => {
        const event = events.find(e => {
            const venue = e.venue || '';
            return venue.toLowerCase().includes(cityKeyword.toLowerCase());
        });
        
        if (event) {
            uniqueCityEvents.push(event);
            citiesFound.add(event.link);
        }
    });

    // 2. Second pass: Fill remaining slots with other events
    const remainingEvents = events.filter(e => !citiesFound.has(e.link));
    
    // Combine and slice
    let displayList = [...uniqueCityEvents, ...remainingEvents];
    
    // Deduplicate
    displayList = displayList.reduce((acc, current) => {
        const x = acc.find(item => item.link === current.link);
        return !x ? acc.concat([current]) : acc;
    }, []).slice(0, 8); 
    
    displayList.forEach(event => {
        const card = document.createElement('article');
        // Card Styles: Consistent Dark Theme
        card.className = 'min-w-[280px] md:min-w-0 snap-center bg-gray-800 rounded-xl overflow-hidden shadow-lg hover:shadow-2xl hover:-translate-y-1 transition-all duration-300 border border-gray-700 hover:border-brand-primary/50 flex flex-col relative group';

        const config = getCityConfig(event.venue);

        // Format Date
        const dateObj = new Date(event.eventDate);
        const dateStr = dateObj.toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            weekday: 'short'
        });
        const timeStr = dateObj.toLocaleTimeString('en-US', { 
            hour: 'numeric', 
            minute: '2-digit',
            timeZone: config.timezone
        });

        card.innerHTML = `
            <div class="p-6 flex flex-col h-full items-center text-center relative z-10">
                
                <!-- Compact Header: Icon + City -->
                <div class="mb-4 flex flex-col items-center">
                    <div class="text-4xl mb-2 filter drop-shadow-lg transform transition-transform group-hover:scale-110">${config.icon}</div>
                    <h3 class="text-2xl font-bold text-white uppercase tracking-tight leading-none">
                        ${config.label}
                    </h3>
                    <div class="h-0.5 w-8 bg-brand-primary rounded-full mx-auto mt-3 opacity-60 group-hover:w-16 transition-all duration-300"></div>
                </div>

                <!-- Registration Notice (Simplified) -->
                ${event.link.includes('meetup.com') ? 
                `<div class="flex items-center gap-1.5 text-gray-500 text-xs mb-4 opacity-80">
                    <span class="text-brand-primary">●</span> RSVP Required
                </div>` : ''}

                <div class="mt-auto w-full">
                    <a href="${event.link}" target="_blank" class="block w-full bg-white/5 hover:bg-brand-primary hover:text-white text-gray-300 border border-white/10 hover:border-transparent font-bold py-3.5 px-4 rounded-lg transition-all duration-300 text-sm backdrop-blur-sm uppercase tracking-wider">
                        Register on Meetup
                    </a>
                </div>
            </div>
            
            <!-- Background Decorative Typography -->
            <div class="absolute -bottom-4 -right-4 text-8xl font-black select-none pointer-events-none text-white opacity-[0.03] overflow-hidden leading-none">
                ${config.short}
            </div>
            
            <!-- Hover Glow Effect -->
            <div class="absolute inset-0 bg-gradient-to-t from-brand-primary/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none"></div>
        `;
        list.appendChild(card);
    });

    container.appendChild(list);
    
    // Add spacer
    const spacer = document.createElement('div');
    spacer.className = 'md:hidden min-w-[1rem]';
    list.appendChild(spacer);
}

function renderNoEvents(container, groupUrl) {
    container.innerHTML = `
        <div class="text-center bg-gray-800/50 p-8 rounded-xl border border-gray-700 border-dashed">
            <p class="text-gray-300 text-lg mb-2">No upcoming events scheduled right now.</p>
            <p class="text-gray-500 text-sm">Join our Meetup group to get notified when we post one!</p>
            <a href="${groupUrl}" target="_blank" class="inline-block mt-4 text-yellow-500 hover:text-yellow-400 font-semibold">
                Visit our Meetup Page &rarr;
            </a>
        </div>
    `;
}

/**
 * Updates the "Meet Your Local Heroes" section links based on upcoming events.
 * Maps specific hosts to their city's next event.
 * @param {Array} events - Sorted list of upcoming events
 */
function updateHeroLinks(events) {
    // Map host IDs to their respective City keywords
    const hostMap = {
        'host-chris': 'Sydney',
        'host-david': 'Melbourne',
        'host-naoki': 'Brisbane',
        'host-kazuma': 'Tokyo',
        'host-hiroshi': 'Fukuoka'
        // Michael is static
    };

    // Default Main Link
    const mainLink = 'https://www.meetup.com/ja-JP/lounge-asia-east-asian-community-mixer-jp-cn-tw-kr';

    Object.keys(hostMap).forEach(hostId => {
        const element = document.getElementById(hostId);
        if (element) {
            const cityKeyword = hostMap[hostId];
            
            // Find the *first* upcoming event for this city
            // Events are already sorted by date in filterAndSortEvents
            const cityEvent = events.find(e => {
                const venue = e.venue || '';
                return venue.toLowerCase().includes(cityKeyword.toLowerCase());
            });

            if (cityEvent && cityEvent.link) {
                element.href = cityEvent.link;
            } else {
                // If no specific event, link to main group page (or keep default if hardcoded)
                // We'll set it to main group page to be safe
                element.href = mainLink;
            }
        }
    });

    // Fukuoka specific handling (since we might no have events yet)
    // If Hiroshi needs a specific fallback (e.g. no events yet), it defaults to mainLink above.
}
